### ISSUE TITLE
Confusion about inmemoryBlockedOnConsumed

### ISSUE THREAD

**Issue by CMatias** [animir/node-rate-limiter-flexible#107]
I'm having a hard time figuring out how `points` and `inmemoryBlockedOnConsumed` complement each other.

From my understanding, [after reading this page](https://github.com/animir/node-rate-limiter-flexible/wiki/In-memory-Block-Strategy#setup-in-memory-block-strategy), once `points` expire, we start consuming `inmemoryBlockedOnConsumed` points and once those expire, we block the key in memory (in the example `points` and `inmemoryBlockedOnConsumed` are both `5`, hence the `if 10 or more points are consumed` we block it.

However, [in this part of the docs](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#apply-in-memory-block-strategy-to-avoid-extra-requests-to-store),  it gives the idea that once the `300` points expire the key will be blocked in memory, so which one is it?

Since `inmemoryBlockedOnConsumed`'s default is 0, it gives the ideia that once `points` expire we immediately block the key in memory, which seems a sensible default. I'm having a hard time understanding why we would want to allow more updates to the store before the in-memory block, is it simply to avoid the latency of removing the in-memory block?

**Comment by animir** [comment]
@CMatias Hi, sorry about confusion. I fixed wrong docs [here](https://github.com/animir/node-rate-limiter-flexible/wiki/In-memory-Block-Strategy#setup-in-memory-block-strategy).

`inmemoryBlockedOnConsumed` option was implemented to avoid extra queries to stores like Redis. When your application grows, it usually consist of many node.js processes/servers, so you need centralised storage for all limit counters. Redis is one of the best. You may omit `inmemoryBlockedOnConsumed` at all, it would work fine. Default 0 for `inmemoryBlockedOnConsumed` means no block in memory, but block using Redis storage. If you set `inmemoryBlockedOnConsumed` to some value N, a key will be blocked in current process memory the moment it consumes N points. After that no requests are sent to Redis, until key expires in memory. 

>  I'm having a hard time understanding why we would want to allow more updates to the store before the in-memory block

Some applications are distributed or/and consist of many processes. We can't rely on memory limiter in this case and use Redis limiter, for example. So all requests made to all node.js processes are counted correctly in one place. That's why `inmemoryBlockedOnConsumed` is additional option, which may help to avoid extra requests to a store.

Imagine, your limiter has 5 points for 10 seconds allowance and `inmemoryBlockedOnConsumed` set to `10`. When user makes 10 requests during the first second, there are still 9 seconds to make more requests. But it is not always necessary to know how many points consumed, if our purpose is to block and nothing else. So, all requests done during remaining 9 seconds don't go to Redis. 

I hope, this helps.

**Comment by CMatias** [comment]
Hi @animir,

Eventually we looked through the source and found out what the intended behavior was. Nonetheless, thanks for updating the docs and for the explanation, I wasn't thinking in terms of distributed systems 🙂
