### ISSUE TITLE
Fix MongoDB DeprecationWarning: collection.findOneAndUpdate option [returnOriginal]

### ISSUE THREAD

**Issue by animir** [animir/node-rate-limiter-flexible#135]
CONTEXT: RateLimiterMongo works without warning for Mongo Client v4+ with [this check](https://github.com/animir/node-rate-limiter-flexible/blob/master/lib/RateLimiterMongo.js#L172). But deprecation was introduced before v4, so some v3.x affected also.

TODO: Find exact version, when deprecation is added and improve mongoDB driver version check in [the condition](https://github.com/animir/node-rate-limiter-flexible/blob/master/lib/RateLimiterMongo.js#L172).

**Comment by pavittarx** [comment]
@animir I was trying to fix it up, but found that `gerDriverVersion()` is only exporting the major version of the driver. So, in order to fix this, `getDriverVersion()` would require changes as well. **Just wanted to make sure, this does not have dependencies somewhere else.**

I have two approaches implementing comparison check. 

1. Converting the version to an integer. For example. version `4.1.3` would be 413, but this would have issues with versions such as 3.6.10 or 3.8.11

2. The other approach is to export as  an object. For example, version "4.1.3" would be `{majorVersion: 4, featureVersion: 1, patchVersion: 3}` which would take three conditional checks. But, better implementation.
