### ISSUE TITLE
How does blockDuration work?

### ISSUE THREAD

**Issue by BroCube** [animir/node-rate-limiter-flexible#138]
Thank you for this amazing library as well as your time. 

[The docs](https://github.com/animir/node-rate-limiter-flexible/wiki/Options#blockduration) are a little vague on the inner workings of `blockDuration`, so I have a few questions:

1) What happens if `blockDuration` is set to (the default value of) `0`? Does it simply throw the relevant error (once all  points are consumed) until `duration` resets? Or does it work the same way as `duration` and `rateLimiter.block(key, secDuration)` in where the block duration will never expire?

   - If the former: is there a way to set `blockDuration` to "never expire" when defining the limiter? Or is the only way to use `rateLimiter.block(key, secDuration)` with `secDuration` set to 0?

   - If the latter:  Inversely to the above, is there a way to set it to "only throw errors until `duration` resets" other than just setting `duration` and `blockDuration` as the same number?

2) Whichever method accomplishes blocks to "never expire", on `RateLimiterMemory`, will this have the same limitation as `duration` [where the max duration is about 24 days](https://github.com/animir/node-rate-limiter-flexible/wiki/Memory#ratelimitermemory)?

3) When using `blockDuration` in conjunction with the `rateLimiter.block(key, secDuration)` function, what takes priority? Is this true even if `secDuration` is set to `0` (or undefined)?

4) If `blockDuration` is set lower than `duration` and someone exceeds their points, do their consumed points reset to 0 after `blockDuration` expires? Or (assuming they're in the same `duration` period) are they still at max points and would immediately trigger the block again?

**Comment by animir** [comment]
@BroCube Hi, thank you.
I'll do my best:
1. `blockDuration` option doesn't work until it is positive number. If it is default `0` limiter works as it is supposed to without any additional block. It doesn't throw any error if `blockDuration` set to `0`, when all points consumed. I improved `blockDuration` docs.
    - The former: `blockDuration` option can't block a key for forever. We can change this in the next major release though. I understand the confusion between `blockDuration` option and `rateLimiter.block(key, secDuration)` function.
    - The latter: this is how limiter works without `blockDuration` options. It rejects the `consume` call when a key has more than `points` in current `duration`.
2. `RateLimiterMemory` can block key forever, as it doesn't require to set any timeout. Any other block duration has the same `about 24 days` limit, yes.
3. There should be no priorities between `blockDuration` and `rateLimiter.block(key, secDuration)` functions, the latter call overwrites previous `expire` set under the hood. No matter what is `blockDuration` set to, `rateLimiter.block(key, secDuration)` method can block a key forever.
4. I am not sure, what happens if `blockDuration` is set lower than `duration`. Could provide an example, how would you use this ability?

Nice questions, thanks.

**Comment by animir** [comment]
@BroCube Closing this, feel free to re-open, if you still have questions
