### ISSUE TITLE
Using rate-limit-flexible with cloudflare workers

### ISSUE THREAD

**Issue by LGmatrix13** [animir/node-rate-limiter-flexible#154]
Hey there,

So I am thinking of transitioning my backend to cloudflare workers. Will rate-limit-flexible work with it? Cloudflare workers is stateless so I'm unsure. Also, they seem to have something called durable object storage: https://developers.cloudflare.com/workers/learning/using-durable-objects. However, I still think this would be challenging to integrate with rate-limit-flexible. What also is confusing is that cloudflare mentions you can persist memory across their edge network: https://developers.cloudflare.com/workers/platform/limits#memory.

Would anyone be able to shed some light on whether using rate-limiter-flexible is possible with cloudflare workers? Thanks!

**Comment by animir** [comment]
@LGmatrix13 Hey.
Which type of limiter from `rate-limiter-flexible` do you use? I presume, you use `RateLimiterMemory`?

I think, it is possible to implement a new type of limiter `RateLimiterCloudFlare`, since there is this counter example https://developers.cloudflare.com/workers/learning/using-durable-objects#example---counter. However, performance of this approach could be low because of additional concurrency block during increment operation, as this is the only way increment can be atomic on CloudFlare. Also, there is no TTL, so it would require TTL as separate value stored with Durable Objects. Worth trying, if you are not in harry.

Regarding storing in memory between requests, here is a quote from the https://developers.cloudflare.com/workers/platform/limits#memory  `nodes are occasionally evicted from memory`, that means it can not be used across all node(s).

**Comment by LGmatrix13** [comment]
I am currently using the `RateLimterMemory`. Regarding the issue about memory eviction: does that mean the memory is not the same across the network? Even if the memory was just for one worker's instance (i.e. the one closest to the user) would it even matter because that would be the only one the user is communicating to? I guess the only way they could get away is by using a VPN, but they could do that as well on any server due to the change of an IP address.

The last resort for me is using Redis with upstash, but I personally don't want to have to deal with another database....

Thank you for your insight regardless!!
