### ISSUE TITLE
RateLimiterPostgres ignore case while postgres tables can be case sensitive

### ISSUE THREAD

**Issue by searchableguy** [animir/node-rate-limiter-flexible#197]
I'm using this package with an existing application where we have tables in CamelCase for historical reasons. I've created rate limiting table using sequelize which we use for migration. 

I noticed it wasn't getting recognized because the code always assume table names are in lower case. 

https://github.com/animir/node-rate-limiter-flexible/blob/master/lib/RateLimiterPostgres.js#L225

This causes the rate limiter to fail. 

I resolved it by using lower cased table but wanted to file an issue since I didn't find any existing ones.

**Comment by animir** [comment]
@searchableguy Hi, thanks for reporting this.

You shared a link to the line where `prefix` variable is calculated. It isn't related to SQL query preparation, but named statement.

But I get you the issue. Postgres requires quoted table name if it needs to be case sensitive.
Current implementation uses table name string without quotes, so it is lower cased by Postgres server itself. That's how Postgres works.

The fix for this issue may go in the next major release.
Are you willing to prepare a fix?

**Comment by searchableguy** [comment]
@animir Yes, I can try to open a PR for the fix.

**Comment by animir** [comment]
Released in `3.0.1`. Thanks to @komachi

**Comment by searchableguy** [comment]
Thanks @komachi I forgot about this after working around this problem.
