### ISSUE TITLE
`enableOfflineQueue` in redis client

### ISSUE THREAD

**Issue by posquit0** [animir/node-rate-limiter-flexible#37]
### Question

- Why the redis client should be configured as `enableOfflineQueue: false`? When I tried without this option, `rate-limit` does work well.

**Comment by animir** [comment]
@posquit0 This is really good question. 
Imagine, there are 2 node.js processes. Some requests go to the first and some go to the second process. Imagine, redis connection is not established yet. It means, there are 2 offline queues on every process. It is impossible to control which order requests will be processed, because every node.js process does it asynchronously. 

You can enable offline queues, but keep that in mind.
I'm going to put a note about it to wiki.
Thank you for the question.

**Comment by posquit0** [comment]
Thanks for your reply. However, I cannot agree with that. A similar problem can happen when 2 node.js process has different network latency. I think the order which redis server received is more important in the distributed system.

Is there any critical example why `enableOfflineQueue: false` is the matter?

**Comment by animir** [comment]
@posquit0 Another example, your servers processes 5000 requests per second, then your Redis is down for 30 seconds by some reason. 600000 requests are queued and going to be processed and in the same time usual 5000 requests per second. This may cause different unexpected issues, like slow down servers.

May be your server shouldn't queue requests and should response immediately if Redis is not accessible.

Offline queue gives different drawbacks. If developer knows them, he can enable offline queue, but I prefer to keep it disabled on open-source docs as it helps developers to avoid mistakes.

I've changed wiki page, btw: https://github.com/animir/node-rate-limiter-flexible/wiki/Redis

**Comment by posquit0** [comment]
Many scheduling system like k8s has liveness check and readiness check feature. I think the circuit breaker should be executed with proper readiness check configuration in the situation you suggested.

Briefly, the service should deny the request when they are not ready to receive the request. The definition of readiness check in k8s is following:

> Sometimes, applications are temporarily unable to serve traffic. For example, an application might need to load large data or configuration files during startup, or depend on external services after startup. In such cases, you don’t want to kill the application, but you don’t want to send it requests either.

So, I think `enableOfflineQueue` option should be **optional**, not **should be**. :)

- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by animir** [comment]
@posquit0 There was also another reason of disabling offline queue.
Since this package supports both `node_redis` and `ioredis` client packages, I do not want to bring any complications to `rate-limiter-flexible` docs. It works different for `node_redis` and `ioredis`: `node_redis` uses offline queue on all Redis sever fails, but `ioredis` uses it only for requests sent before `ready` event.

**Comment by animir** [comment]
closing this. be free to re-open if something comes up
