### ISSUE TITLE
Negative points and duration values allowed for new RateLimiter

### ISSUE THREAD

**Issue by jinshunlee** [animir/node-rate-limiter-flexible#47]
Hi, I realised that negative values are allowed for `points` and `duration` when you initialise a `RateLimiter`, should this return an error instead as it does not make sense to have negative values for `points` and `duration`.

**Comment by animir** [comment]
@jinshunlee Negative `points` option is fine, since there is `reward` method. May be developer wants to implement some logic, where all keys are blocked, until they do something to increase their points.

`duration` option is definitely must not be negative. It is usually clear as it is. However, it is never bad to have such a simple validation. Please, create PR if you implement it.
