### ISSUE TITLE
Adding a new Rate Limiter Store 

### ISSUE THREAD

**Issue by eabait** [animir/node-rate-limiter-flexible#85]
Hi

I'm trying to extend this library with a new store for Dynamodb. I'm trying to do this from my application. However, when I extend class RateLimiterStoreAbstract I can't access `this.points` due to the following error: `Property 'points' does not exist on type`.

Do you know how I can do it?

Regards
Esteban

**Comment by animir** [comment]
@eabait Hi, that's weird. I see `this.points` is used in other classes of this package. Could you provide your code?

**Comment by animir** [comment]
@eabait Hi, how is it going? were you able to implement DynamoDB limiter?

**Comment by eabait** [comment]
Hi @animir 

I had to do the following:
```
import 'rate-limiter-flexible';

/**
 * This type definition augments existing definition
 * from package rate-limiter-flexible
 */
declare module 'rate-limiter-flexible' {
  interface RateLimiterAbstract {
    points: number;
  }
}
```
Hopes it helps for future reference.

On the other hand, I would like to know more about the _upsert operation. I had implemented a version using Dynamodb, but I had to use several operations (1 getItem, 1 putItem) instead of using Dynamo's update operator. This is because I followed the logic in the Postgres Store to implement _upsert.
Could you tell me about the pre/pos conditions an _upsert operation must satisfy?

Thanks
Esteban

**Comment by animir** [comment]
@eabait Hi. If you use Typescript and your environment requires `points` to be defined, you can add it to `index.ts` to class RateLimiterAbstract. Then create PR here.

1. First of all, `upsert` must be atomic. It means, no race conditions can affect lost increments. 
2. Upsert also should insert a new key/value pair, if there is no such key. Otherwise, upsert must increment existing value.
3. Finally, upsert should force update key expire, if the forth argument `forceExpire` is true.

I think, `update_item` should be used to make counter increment atomic. What do you think?

**Comment by animir** [comment]
@eabait I updated [contribution section of readme](https://github.com/animir/node-rate-limiter-flexible#contribution)

**Comment by eabait** [comment]
Excellent, we can close the issue.

**Comment by trompx** [comment]
Hey @eabait, did you end managing to use dynamodb as a store? I am also interested as it seems redis serveless saas are rather expensive. If yes, would you mind sharing some hints how you did it or maybe you have a repo somewhere with the implementation?
