### ISSUE TITLE
wrong typings?

### ISSUE THREAD

**Issue by yovanoc** [animir/node-rate-limiter-flexible#91]
Hello,

should this be just `res` instead to match typing?

https://github.com/animir/node-rate-limiter-flexible/blob/46647d36765b9485d6e4bface6d9c43a3c33dd26/lib/RateLimiterQueue.js#L72

**Comment by animir** [comment]
Hi,
`RateLimiterQueue` doesn't have types for methods in the class. Also, it doesn't make much sense to return `msBeforeNext` or `consumedPoints` for queue implementation.

**Comment by yovanoc** [comment]
Yes but these methods are wrong typed

https://github.com/animir/node-rate-limiter-flexible/blob/d9a39fb1457f3c7ea683ff37162a846e417f7ec7/lib/index.d.ts#L163
https://github.com/animir/node-rate-limiter-flexible/blob/d9a39fb1457f3c7ea683ff37162a846e417f7ec7/lib/index.d.ts#L165

<img width="811" alt="image" src="https://user-images.githubusercontent.com/7302317/95948915-d367b280-0df1-11eb-9c34-727ac421fa42.png">

I see that with that commented line who give me the same types but this is just the remainingPoints (a number) and I can't use the queue too set my headers

**Comment by animir** [comment]
@yovanoc You're right. There are types for `getTokensRemaining` and `removeTokens` and their result type is wrong. It is supposed to be `Promise<number>`.

> I can't use the queue too set my headers
RateLimiterQueue doesn't return anything except number of remaining tokens (points), as it works completely different way not like any other limiter from this package. Queue processes added request ASAP, but can wait for minutes/hours/days (it depends on settings) before it happens. Because of that, there is no need to set Headers related to `msBeforeNext`.

**Comment by animir** [comment]
@yovanoc I am glad to notify you, Queue methods return types are fixed in version `2.1.13`.

**Comment by yovanoc** [comment]
perfect! thanks :)
